<fetishmaster.engine.TextTemplate>
  <conditions>GetPerFlag(&quot;karin_milk&quot;)&lt;10000</conditions>
  <text>&lt;%
SetPerFlag(&quot;karin_food&quot;,(GetPerFlag(&quot;karin_food&quot;)-10));
 &quot;&quot;;%&gt;</text>
  <priority>0</priority>
  <picturePath></picturePath>
  <choices/>
  <overrideChoices>false</overrideChoices>
</fetishmaster.engine.TextTemplate>