<fetishmaster.engine.TextTemplate>
  <conditions>1</conditions>
  <text>&lt;% &#xd;
img = &quot;char/merril_nn_em.png&quot;;&#xd;
mlust = merril.getStat(&quot;generic.arousal&quot;);&#xd;
mbelly = merril.getStat(&quot;generic.abdomen&quot;);&#xd;
mballs = merril.getStat(&quot;balls.size&quot;);&#xd;
&#xd;
sysprint (&quot;merill arousal: &quot; + mlust);&#xd;
sysprint(&quot;merril belly: &quot; + mbelly);&#xd;
if (mballs &lt; 34)&#xd;
{&#xd;
if (mlust &lt; 30)&#xd;
{&#xd;
	if (mbelly &gt; 4)&#xd;
	{ img = &quot;char/merril_nn_full.png&quot;;}&#xd;
}&#xd;
else&#xd;
{&#xd;
	if (mbelly &gt; 4)&#xd;
	{ img = &quot;char/merril_nu_full.png&quot;;}&#xd;
	if (mbelly &gt; 4 &amp;&amp; mlust &gt; 50)&#xd;
	{ img = &quot;char/merril_nu_full_ar.png&quot;;}&#xd;
}&#xd;
}&#xd;
if (mballs &gt;= 34)&#xd;
{&#xd;
	if (mlust &lt; 30)&#xd;
	{	&#xd;
		if (mbelly &lt;= 4)&#xd;
		{&#xd;
		if (mballs &lt; 42)&#xd;
		{ img = &quot;char/merril_nn_em_big1.png&quot;;}&#xd;
		if (mballs &lt; 68 &amp;&amp; mballs &gt;= 42)&#xd;
		{ img = &quot;char/merril_nn_em_big2.png&quot;;}&#xd;
		if (mballs &lt; 94 &amp;&amp; mballs &gt;= 68)&#xd;
		{ img = &quot;char/merril_nn_em_big3.png&quot;;}&#xd;
		if (mballs &lt; 120 &amp;&amp; mballs &gt;= 94)&#xd;
		{ img = &quot;char/merril_nn_em_big4.png&quot;;}&#xd;
		if (mballs &gt;= 120)&#xd;
		{ img = &quot;char/merril_nn_em_big5.png&quot;;}&#xd;
		}&#xd;
		if (mbelly &gt; 4)&#xd;
		{&#xd;
		if (mballs &lt; 42)&#xd;
		{ img = &quot;char/merril_nn_full_big1.png&quot;;}&#xd;
		if (mballs &lt; 68 &amp;&amp; mballs &gt;= 42)&#xd;
		{ img = &quot;char/merril_nn_full_big2.png&quot;;}&#xd;
		if (mballs &lt; 94 &amp;&amp; mballs &gt;= 68)&#xd;
		{ img = &quot;char/merril_nn_full_big3.png&quot;;}&#xd;
		if (mballs &lt; 120 &amp;&amp; mballs &gt;= 94)&#xd;
		{ img = &quot;char/merril_nn_full_big4.png&quot;;}&#xd;
		if (mballs &gt;= 120)&#xd;
		{ img = &quot;char/merril_nn_full_big5.png&quot;;}&#xd;
		}&#xd;
	}&#xd;
	if (mlust &gt;= 30)&#xd;
	{	&#xd;
		if (mbelly &lt; 4)&#xd;
		{&#xd;
			if (mballs &lt; 42)&#xd;
			{ img = &quot;char/merril_nu_em_big1.png&quot;;}&#xd;
			if (mballs &lt; 68 &amp;&amp; mballs &gt;= 42)&#xd;
			{ img = &quot;char/merril_nu_em_big2.png&quot;;}&#xd;
			if (mballs &lt; 94 &amp;&amp; mballs &gt;= 68)&#xd;
				{&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &lt; 1)&#xd;
				{ img = &quot;char/merril_nu_em_big3.png&quot;;}&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &gt;= 1)&#xd;
				{ img = &quot;char/merril_nu_em_big3.png&quot;;}&#xd;
				}&#xd;
			if (mballs &lt; 120 &amp;&amp; mballs &gt;= 94)&#xd;
			{ img = &quot;char/merril_nu_em_big4.png&quot;;}&#xd;
			if (mballs &gt;= 120)&#xd;
			{ img = &quot;char/merril_nu_em_big5.png&quot;;}&#xd;
		}&#xd;
		if (mbelly &gt; 4 &amp;&amp; mlust &lt; 50)&#xd;
		{&#xd;
			if (mballs &lt; 42)&#xd;
			{ img = &quot;char/merril_nu_full_big1.png&quot;;}&#xd;
			if (mballs &lt; 68 &amp;&amp; mballs &gt;= 42)&#xd;
			{ img = &quot;char/merril_nu_full_big2.png&quot;;}&#xd;
			if (mballs &lt; 94 &amp;&amp; mballs &gt;= 68)&#xd;
				{&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &lt; 1)&#xd;
				{ img = &quot;char/merril_nu_full_big3.png&quot;;}&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &gt;= 1)&#xd;
				{ img = &quot;char/merril_nu_full_big3.png&quot;;}&#xd;
				}&#xd;
			if (mballs &lt; 120 &amp;&amp; mballs &gt;= 94)&#xd;
			{ img = &quot;char/merril_nu_full_big4.png&quot;;}&#xd;
			if (mballs &gt;= 120)&#xd;
			{ img = &quot;char/merril_nu_full_big5.png&quot;;}&#xd;
		}&#xd;
		if (mlust &gt;= 50)&#xd;
		{&#xd;
			if (mbelly &gt; 4)&#xd;
			{&#xd;
				if (mballs &lt; 42)&#xd;
				{ img = &quot;char/merril_nu_full_ar_big1.png&quot;;}&#xd;
				if (mballs &lt; 68 &amp;&amp; mballs &gt;= 42)&#xd;
				{&#xd;
				if (GetFlag(&quot;merril_cock_growth1&quot;) &lt; 1)&#xd;
				{ img = &quot;char/merril_nu_full_ar_big2.png&quot;;}&#xd;
				if (GetFlag(&quot;merril_cock_growth1&quot;) &gt;= 1)&#xd;
				{ img = &quot;char/merril_nu_full_ar_big2_cock1.png&quot;;}&#xd;
				}&#xd;
				if (mballs &lt; 94 &amp;&amp; mballs &gt;= 68)&#xd;
				{&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &lt; 1)&#xd;
				{ img = &quot;char/merril_nu_full_ar_big3_cock2.png&quot;;}&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &gt;= 1)&#xd;
				{ img = &quot;char/merril_nu_full_ar_big3_cock3.png&quot;;}&#xd;
				}&#xd;
				if (mballs &lt; 120 &amp;&amp; mballs &gt;= 94)&#xd;
				{ img = &quot;char/merril_nu_full_ar_big4_cock4.png&quot;;}&#xd;
				if (mballs &gt;= 120)&#xd;
				{ img = &quot;char/merril_nu_full_ar_big5.png&quot;;}&#xd;
			}&#xd;
			if (mbelly &lt; 4)&#xd;
			{&#xd;
				if (mballs &lt; 42)&#xd;
				{ img = &quot;char/merril_nu_em_ar_big1.png&quot;;}&#xd;
				if (mballs &lt; 68 &amp;&amp; mballs &gt;= 42)&#xd;
				{&#xd;
				if (GetFlag(&quot;merril_cock_growth1&quot;) &lt; 1)&#xd;
				{ img = &quot;char/merril_nu_em_ar_big2.png&quot;;}&#xd;
				if (GetFlag(&quot;merril_cock_growth1&quot;) &gt;= 1)&#xd;
				{ img = &quot;char/merril_nu_em_ar_big2_cock1.png&quot;;}&#xd;
				}&#xd;
				if (mballs &lt; 94 &amp;&amp; mballs &gt;= 68)&#xd;
				{&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &lt; 1)&#xd;
				{ img = &quot;char/merril_nu_em_ar_big3_cock2.png&quot;;}&#xd;
				if (GetFlag(&quot;merril_cock_growth3&quot;) &gt;= 1)&#xd;
				{ img = &quot;char/merril_nu_em_ar_big3_cock3.png&quot;;}&#xd;
				}&#xd;
				if (mballs &lt; 120 &amp;&amp; mballs &gt;= 94)&#xd;
				{ img = &quot;char/merril_nu_em_ar_big4_cock4.png&quot;;}&#xd;
				if (mballs &gt;= 120)&#xd;
				{ img = &quot;char/merril_nu_em_ar_big5.png&quot;;}&#xd;
			}&#xd;
		}&#xd;
	}&#xd;
	&#xd;
}&#xd;
DisplayChar(img);&#xd;
&quot;&quot;;%&gt;</text>
  <priority>0</priority>
  <picturePath></picturePath>
  <choices/>
  <overrideChoices>false</overrideChoices>
</fetishmaster.engine.TextTemplate>